### PR TITLE
Bugfix in common_db_query

### PR DESCRIPTION
**Pull request by erdebee**
Removed typo (two occurrences of '*') that made this file unparseable

### CODE REVIEW

**Comment by DottoreTozzi** [comment]
That's actually not a typo.

**Comment by DottoreTozzi** [comment]
Sorry, closed it accidentally (damn "magic" mouse).
The ** operator means "power of", according to the standard polynomial expression of
ax^2 + bx + c

What do you mean by "unparseable"?
From php 5.6 onwards, this would be the recommended approach.
For earlier versions, you might want to use the pow() function.

**Comment by erdebee** [comment]
Ah, im running php 5.4, the php that ships with centos 7 by default. Perhaps you could stick with pow() as it has broader support then?
Php gave me a syntax error on this statement.

**Comment by DottoreTozzi** [comment]
I'd rather not use a function that has basically been deprecated in the newer versions.
But I'll look into it.

**Comment by DottoreTozzi** [comment]
I have changed it to pow() now for backwards compatibility.

**Pull request closed without merging**
